In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('IRIS.csv')

data

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
selected_columns=data[['sepal_length','sepal_width']]
selected_columns

sepal_length  sepal_width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [5]:
filtered_data=data[data['sepal_length']>5]
filtered_data

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
5             5.4          3.9           1.7          0.4     Iris-setosa
10            5.4          3.7           1.5          0.2     Iris-setosa
14            5.8          4.0           1.2          0.2     Iris-setosa
15            5.7          4.4           1.5          0.4     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[118 rows x 5 columns]

In [6]:
data.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [7]:
data.values

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [8]:
data['species'].value_counts()

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [9]:
grouped_data=data.groupby('species').sum()
grouped_data

sepal_length  sepal_width  petal_length  petal_width
species                                                              
Iris-setosa             250.3        170.9          73.2         12.2
Iris-versicolor         296.8        138.5         213.0         66.3
Iris-virginica          329.4        148.7         277.6        101.3

In [10]:
grouped_data=data.groupby('sepal_length')['sepal_width'].sum()
grouped_data

sepal_length
4.3     3.0
4.4     9.1
4.5     2.3
4.6    13.3
4.7     6.4
4.8    15.9
4.9    17.2
5.0    31.2
5.1    31.3
5.2    13.7
5.3     3.7
5.4    21.3
5.5    19.9
5.6    16.9
5.7    24.8
5.8    20.2
5.9     9.2
6.0    16.4
6.1    17.1
6.2    11.3
6.3    25.7
6.4    20.7
6.5    15.0
6.6     5.9
6.7    24.4
6.8     9.0
6.9    12.5
7.0     3.2
7.1     3.0
7.2     9.8
7.3     2.9
7.4     2.8
7.6     3.0
7.7    12.2
7.9     3.8
Name: sepal_width, dtype: float64

In [11]:
grouped_data=data.groupby('sepal_width')['sepal_length'].sum()
grouped_data

sepal_width
2.0      5.0
2.2     18.2
2.3     21.3
2.4     15.9
2.5     46.1
2.6     30.8
2.7     52.7
2.8     88.7
2.9     60.6
3.0    156.4
3.1     71.3
3.2     76.5
3.3     36.1
3.4     63.8
3.5     30.9
3.6     16.8
3.7     15.8
3.8     36.6
3.9     10.8
4.0      5.8
4.1      5.2
4.2      5.5
4.4      5.7
Name: sepal_length, dtype: float64

In [12]:
grouped_data=data.groupby('petal_length')['petal_width'].sum()
grouped_data

petal_length
1.0     0.2
1.1     0.1
1.2     0.4
1.3     1.8
1.4     2.6
1.5     3.1
1.6     2.0
1.7     1.4
1.9     0.6
3.0     1.1
3.3     2.0
3.5     2.0
3.6     1.3
3.7     1.0
3.8     1.1
3.9     3.7
4.0     6.1
4.1     3.6
4.2     5.3
4.3     2.6
4.4     5.3
4.5    12.1
4.6     4.2
4.7     7.1
4.8     6.8
4.9     8.6
5.0     7.1
5.1    15.4
5.2     4.3
5.3     4.2
5.4     4.4
5.5     5.7
5.6    12.3
5.7     6.9
5.8     5.6
5.9     4.4
6.0     4.3
6.1     6.7
6.3     1.8
6.4     2.0
6.6     2.1
6.7     4.2
6.9     2.3
Name: petal_width, dtype: float64

In [13]:
grouped_data=data.groupby('petal_width')['petal_length'].sum()
grouped_data

petal_width
0.1     8.5
0.2    40.4
0.3    10.0
0.4    11.0
0.5     1.7
0.6     1.6
1.0    25.4
1.1    10.7
1.2    21.2
1.3    54.3
1.4    37.1
1.5    55.9
1.6    20.1
1.7     9.5
1.8    64.0
1.9    26.6
2.0    33.3
2.1    34.7
2.2    18.1
2.3    45.6
2.4    16.3
2.5    17.8
Name: petal_length, dtype: float64

In [14]:
data1=data[['petal_length','petal_width','species']]
data2=data[['sepal_length','sepal_width','species']]

print(data1)
print(data2)


     petal_length  petal_width         species
0             1.4          0.2     Iris-setosa
1             1.4          0.2     Iris-setosa
2             1.3          0.2     Iris-setosa
3             1.5          0.2     Iris-setosa
4             1.4          0.2     Iris-setosa
..            ...          ...             ...
145           5.2          2.3  Iris-virginica
146           5.0          1.9  Iris-virginica
147           5.2          2.0  Iris-virginica
148           5.4          2.3  Iris-virginica
149           5.1          1.8  Iris-virginica

[150 rows x 3 columns]
     sepal_length  sepal_width         species
0             5.1          3.5     Iris-setosa
1             4.9          3.0     Iris-setosa
2             4.7          3.2     Iris-setosa
3             4.6          3.1     Iris-setosa
4             5.0          3.6     Iris-setosa
..            ...          ...             ...
145           6.7          3.0  Iris-virginica
146           6.3          2.5  Iris

In [15]:
merged_data=pd.merge(data1,data2,on='species')
merged_data

petal_length  petal_width         species  sepal_length  sepal_width
0              1.4          0.2     Iris-setosa           5.1          3.5
1              1.4          0.2     Iris-setosa           4.9          3.0
2              1.4          0.2     Iris-setosa           4.7          3.2
3              1.4          0.2     Iris-setosa           4.6          3.1
4              1.4          0.2     Iris-setosa           5.0          3.6
...            ...          ...             ...           ...          ...
7495           5.1          1.8  Iris-virginica           6.7          3.0
7496           5.1          1.8  Iris-virginica           6.3          2.5
7497           5.1          1.8  Iris-virginica           6.5          3.0
7498           5.1          1.8  Iris-virginica           6.2          3.4
7499           5.1          1.8  Iris-virginica           5.9          3.0

[7500 rows x 5 columns]

In [16]:
data.fillna(0,inplace=True)
data

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [17]:
def process_value(value):
    processed_value=value*2
    return processed_value
data['processed_coloumn']=data['sepal_length'].apply(process_value)
data

sepal_length  sepal_width  petal_length  petal_width         species  \
0             5.1          3.5           1.4          0.2     Iris-setosa   
1             4.9          3.0           1.4          0.2     Iris-setosa   
2             4.7          3.2           1.3          0.2     Iris-setosa   
3             4.6          3.1           1.5          0.2     Iris-setosa   
4             5.0          3.6           1.4          0.2     Iris-setosa   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3  Iris-virginica   
146           6.3          2.5           5.0          1.9  Iris-virginica   
147           6.5          3.0           5.2          2.0  Iris-virginica   
148           6.2          3.4           5.4          2.3  Iris-virginica   
149           5.9          3.0           5.1          1.8  Iris-virginica   

     processed_coloumn  
0                 10.2  
1                  9.8  
2                  9.4  
3                  9.2  
4                 10.0  
..                 ...  
145               13.4  
146               12.6  
147               13.0  
148               12.4  
149               11.8  

[150 rows x 6 columns]

In [18]:
pivot_table=pd.pivot_table(data,values='sepal_length',index='sepal_width',columns='species')
pivot_table

species      Iris-setosa  Iris-versicolor  Iris-virginica
sepal_width                                              
2.0                  NaN         5.000000             NaN
2.2                  NaN         6.100000        6.000000
2.3             4.500000         5.600000             NaN
2.4                  NaN         5.300000             NaN
2.5                  NaN         5.625000        5.900000
2.6                  NaN         5.666667        6.900000
2.7                  NaN         5.680000        6.075000
2.8                  NaN         6.150000        6.475000
2.9             4.400000         6.085714        6.800000
3.0             4.700000         5.950000        6.716667
3.1             4.820000         6.766667        6.725000
3.2             4.680000         6.433333        6.760000
3.3             5.050000         6.300000        6.566667
3.4             5.033333         6.000000        6.250000
3.5             5.150000              NaN             NaN
3.6             4.800000              NaN        7.200000
3.7             5.266667              NaN             NaN
3.8             5.250000              NaN        7.800000
3.9             5.400000              NaN             NaN
4.0             5.800000              NaN             NaN
4.1             5.200000              NaN             NaN
4.2             5.500000              NaN             NaN
4.4             5.700000              NaN             NaN

In [19]:
pivot_table=pd.pivot_table(data,values='sepal_length',index='petal_length',columns='species')
pivot_table

species       Iris-setosa  Iris-versicolor  Iris-virginica
petal_length                                              
1.0              4.600000              NaN             NaN
1.1              4.300000              NaN             NaN
1.2              5.400000              NaN             NaN
1.3              4.842857              NaN             NaN
1.4              4.916667              NaN             NaN
1.5              5.128571              NaN             NaN
1.6              4.914286              NaN             NaN
1.7              5.400000              NaN             NaN
1.9              4.950000              NaN             NaN
3.0                   NaN         5.100000             NaN
3.3                   NaN         4.950000             NaN
3.5                   NaN         5.350000             NaN
3.6                   NaN         5.600000             NaN
3.7                   NaN         5.500000             NaN
3.8                   NaN         5.500000             NaN
3.9                   NaN         5.533333             NaN
4.0                   NaN         5.780000             NaN
4.1                   NaN         5.700000             NaN
4.2                   NaN         5.725000             NaN
4.3                   NaN         6.300000             NaN
4.4                   NaN         6.275000             NaN
4.5                   NaN         5.900000        4.900000
4.6                   NaN         6.400000             NaN
4.7                   NaN         6.440000             NaN
4.8                   NaN         6.350000        6.100000
4.9                   NaN         6.600000        6.000000
5.0                   NaN         6.700000        6.000000
5.1                   NaN         6.000000        6.142857
5.2                   NaN              NaN        6.600000
5.3                   NaN              NaN        6.400000
5.4                   NaN              NaN        6.550000
5.5                   NaN              NaN        6.566667
5.6                   NaN              NaN        6.366667
5.7                   NaN              NaN        6.766667
5.8                   NaN              NaN        6.800000
5.9                   NaN              NaN        6.950000
6.0                   NaN              NaN        6.750000
6.1                   NaN              NaN        7.433333
6.3                   NaN              NaN        7.300000
6.4                   NaN              NaN        7.900000
6.6                   NaN              NaN        7.600000
6.7                   NaN              NaN        7.700000
6.9                   NaN              NaN        7.700000

In [20]:
data['date_column']=pd.to_datetime(data['sepal_length'])
print(data)

# data.set_index('date_column',inplace=True)
# resampled_data=data.resamole('M').sum()
# resampled_data

     sepal_length  sepal_width  petal_length  petal_width         species  \
0             5.1          3.5           1.4          0.2     Iris-setosa   
1             4.9          3.0           1.4          0.2     Iris-setosa   
2             4.7          3.2           1.3          0.2     Iris-setosa   
3             4.6          3.1           1.5          0.2     Iris-setosa   
4             5.0          3.6           1.4          0.2     Iris-setosa   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3  Iris-virginica   
146           6.3          2.5           5.0          1.9  Iris-virginica   
147           6.5          3.0           5.2          2.0  Iris-virginica   
148           6.2          3.4           5.4          2.3  Iris-virginica   
149           5.9          3.0           5.1          1.8  Iris-virginica   

     processed_coloumn                   date_column  
0                 10

In [21]:
data.set_index('date_column',inplace=True)
resambled_data=data.resample('M').sum()
resambled_data

sepal_length  sepal_width  petal_length  petal_width  \
date_column                                                         
1970-01-31          876.5        458.1         563.8        179.8   

                                                       species  \
date_column                                                      
1970-01-31   Iris-setosaIris-setosaIris-setosaIris-setosaIr...   

             processed_coloumn  
date_column                     
1970-01-31              1753.0

In [22]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print("sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print(np.max(arr))
print(np.min(arr))

[1 2 3 4 5]
sum: 15
Mean: 3.0
5
1


In [23]:
arr=np.array([1,2,3,4,5,6])
reshaped_arr=arr.reshape(2,3)
reshaped_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr=np.random.random((3,3))
arr

array([[0.47639593, 0.51766495, 0.72262427],
       [0.54081214, 0.17167365, 0.628696  ],
       [0.79062241, 0.32922104, 0.91242746]])

In [25]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=arr1+arr2
result

array([5, 7, 9])

In [26]:
arr= np.arange(10).reshape((5,2))
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
data=np.array([[1,2],[3,4],[5,6]])
sum_along_rows=np.sum(data,axis=0)
sum_along_columns=np.sum(data,axis=1)
print(sum_along_rows)
print(sum_along_columns)

[ 9 12]
[ 3  7 11]


In [28]:
data=np.arange(10)
mask=data>2
filtered_data=data[mask]
filtered_data

array([3, 4, 5, 6, 7, 8, 9])

In [29]:
data=np.array({1,2,2,3,3,4,4,4,4})
unique_elements=np.unique(data)
data

array({1, 2, 3, 4}, dtype=object)

In [30]:
elements_counts=np.bincount(data)
data

ValueError: object of too small depth for desired array

In [ ]:
elements_counts=np.bincount(data)
elements_counts

ValueError: object of too small depth for desired array

In [ ]:
data=np.array([1,2,23,23,33,3,3,4,4,4,1])
elements_counts=np.bincount(data)
datad

array([ 1,  2, 23, 23, 33,  3,  3,  4,  4,  4,  1])

In [ ]:
data=np.array([1,2,23,23,33,3,3,4,4,4,1])
elements_counts=np.bincount(data)
elements_counts


array([0, 2, 1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [ ]:
x=np.array([1,2,3,4,5])
y=np.array([2,4,5,4,5])
coefficients=np.polyfit(x,y,1)
slope,intercept=coefficients
print("slope:",slope)
print("Intercept:",intercept)

slope: 0.6
Intercept: 2.199999999999999
